### ISSUE TITLE
Create a "Looking for Project / Looking for Contributor" app

### ISSUE THREAD

**Issue by erickt** [rust-community/team#63] opened 2016-08-29 22:36 UTC
As suggested by @jonathandturner: https://github.com/rust-community/team/issues/62#issuecomment-243255636.

**Comment by skade** [comment] 2017-07-29 11:32
#62 and #74 seem related. Is there anyone with more context on the subject that could fold it into one?

**Comment by carols10cents** [comment] 2017-07-29 16:18
i think this can be closed as a duplicate of #74, there's more info/background over there

**Closed by carols10cents** 2017-07-29 16:18 UTC
